apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dbinstances.dbtree.cloud
spec:
  group: dbtree.cloud
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                  enum: [redis, mongodb]
                mode:
                  type: string
                  enum: [basic, replica, cluster]
                version:
                  type: string
                config:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                ownedBy:
                  type: string
                resources:
                  type: object
                  properties:
                    cpu:
                      type: integer
                    memory:
                      type: integer
                    disk:
                      type: integer
                lemonCost:
                  type: object
                  properties:
                    creationCost:
                      type: number
                    hourlyLemons:
                      type: number
                    minimumLemons:
                      type: number
            status:
              type: object
              properties:
                status:
                  type: string
                  enum: [provisioning, running, stopped, paused, error, deleting, maintenance, backing_up, restoring, upgrading]
                statusReason:
                  type: string
                endpoint:
                  type: string
                port:
                  type: integer
                secretRef:
                  type: string
                lemonsBalance:
                  type: number
                lastLemonUpdate:
                  type: string
                  format: date-time
                pauseAfter:
                  type: string
                  format: date-time
                deleteAfter:
                  type: string
                  format: date-time
  scope: Namespaced
  names:
    plural: dbinstances
    singular: dbinstance
    kind: DBInstance
    shortNames: [dbi]