# This rule is not used by the project dbtree-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over dbtree.dbtree.cloud.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dbtree-operator
    app.kubernetes.io/managed-by: kustomize
  name: dbinstance-admin-role
rules:
- apiGroups:
  - dbtree.dbtree.cloud
  resources:
  - dbinstances
  verbs:
  - '*'
- apiGroups:
  - dbtree.dbtree.cloud
  resources:
  - dbinstances/status
  verbs:
  - get
