# This rule is not used by the project dbtree-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to dbtree.dbtree.cloud resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dbtree-operator
    app.kubernetes.io/managed-by: kustomize
  name: dbinstance-viewer-role
rules:
- apiGroups:
  - dbtree.dbtree.cloud
  resources:
  - dbinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbtree.dbtree.cloud
  resources:
  - dbinstances/status
  verbs:
  - get
