apiVersion: dbtree.cloud/v1
kind: DBInstance
metadata:
  name: demo-mongodb
  namespace: user-demo-user-456
spec:
  name: demo-mongodb
  userId: "demo-user-456"
  externalId: "demo-external-id-123"
  type: mongodb
  size: small
  mode: standalone
  secretRef:
    name: demo-mongodb-secret
  resources:
    cpu: 2
    memory: 2048
    disk: 20
  backup:
    enabled: false
  config:
    version: "7.0"
    wiredTigerCache: 1